name: SEmotion-YAMNet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - librosa
  - flake8
  - autopep8
  - notebook
  - jupyterlab
  - pandas
  - scikit-learn
  - pip
  - pip:
    - gitpython
