name: SEmotion-YAMNet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - numpy
  - matplotlib
  - librosa
  - flake8
  - pylint
  - autopep8
  - notebook
  - jupyterlab
  - seaborn
  - pyaudio
  - scikit-learn
  - pip
  - pip:
      - gitpython
      - tensorflow
      - keract
      - tensorflow-datasets
      - tensorflow-io
